### ISSUE TITLE
Google Tag Manager Patch cannot apply during composer install

### ISSUE THREAD

**Issue by DerekCresswell** [AcroMedia/drupal-orange-project#7]
```
"drupal/commerce_google_tag_manager": {
        "Use product variation SKU if available instead of product ID": "https://www.drupal.org/files/issues/2019-07-10/use-product-variation-sku-if-available-3066949-2.patch"
      }
```  
This patch brings up an error when running `Composer Install` for a new project, `Could not apply patch`.  
[Refrence to issue on Drupal](https://www.drupal.org/node/3066949)  
Removing the patch from `composer.json` allowed me to finish the `composer install` and get the rest of the files installed.

**Comment by 7o7o** [comment]
Same issue here when running the recommended installation:
`composer create-project acromedia/drupal-orange-project some-dir --stability dev --no-interaction`

After removing the confictive patch i run `composer install` and installation finishes but some files were not generated, like index.php and all the root files and also some files in the sites folder were missing. 

I had to also run `composer drupal:scaffold` to get those files generated.

**Comment by smmccabe** [comment]
Posted a new re-rolled patch to d.o and updated the composer file in this PR #8

**Comment by cbildstein** [comment]
PR #8 merged. We can now all get along.
